config/routes.rb
Alphachezzles::Application.routes.draw do

  root :to => 'pages#home'

  match '/dash',                                to: 'pages#dash'
  match '/profile',                             to: 'pages#profile'
  match '/about/mission',                       to: 'pages#about/mission'

  match '/help/faq',                            to: 'pages#help/faq'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def dash
  end

  def profile
  end

  def about
    def mission
    end

    def team
    end

    def centres
    end

    def schools
    end
  end

  def help
    def faq
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # returns page title on a per-page basis
  def full_title(page_title)
    base_title = 'Welcome to Chezzles'
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <div class="container">
        <nav>
          <div class="row">
            <div class="span2">
                <ul>
                    <li class="footer-head-list-item"> About </li>
                    <li> <%= link_to "Mission", about_mission_path %></li>
                    <li> <%= link_to "Team", '#' %></li>
                    <li> <%= link_to "Centres", '#' %></li>
                    <li> <%= link_to "Schools", '#' %></li>
                </ul>
            </div>

            <div class="span2">
                <ul>
                    <li class="footer-head-list-item"> Help </li>
                    <li> <%= link_to "FAQ", help_faq_path %></li>
                </ul>
            </div>

            <div class="span2">
                <ul>
                    <li class="footer-head-list-item"> Career </li>
                    <li> <%= link_to "Full Time", '#' %></li>
                    <li> <%= link_to "Part Time", '#' %></li>
                    <li> <%= link_to "Internship", '#' %></li>
                </ul>
            </div>

            <div class="span2">
                <ul>
                    <li class="footer-head-list-item"> Social </li>
                    <li> <%= link_to "Facebook", '#' %></li>
                    <li> <%= link_to "Twitter", '#' %></li>
                    <li> <%= link_to "Blog", '#' %></li>
                </ul>
            </div>

            <div class="span2">
                <ul>
                    <li class="footer-head-list-item"> Contact Us</li>
                    <li> <%= link_to "Contact", '#' %></li>
                    <li> <%= link_to "Press", '#' %></li>
                </ul>
            </div>
          </div>
        </nav>
    </div>

    <div class="container">
        <nav class="sub-footer">
            <div class="span6">
                <small>
                    <a href="http://www.zugzwang.in"> © ZugZwang Chess School </a>
                </small>
            </div>

            <div class="span2 pull-right">
                <ul>
                    <li> <%= link_to "Terms of Use", '#' %></li>
                </ul>
            </div>

            <div class="span2 pull-right">
                <ul>
                    <li> <%= link_to "Privacy Policy", '#' %></li>
                </ul>
            </div>
        </nav>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <div class="row">
        <nav class="span5">
          <ul class="nav pull-left">
            <li> <%= link_to "Home", root_path %></li>
            <li> <%= link_to "Dash", dash_path %></li>
            <li> <%= link_to "Profile", profile_path %></li>
          </ul>
        </nav>

        <nav class="span3">
          <ul class="nav">
            <li> <%= link_to "Chezzles", '#', id: "logo" %> </li>
          </ul>
        </nav>

        <nav class="pull-right">
          <!--ul class="nav pull-right"-->
            <div class="btn-group">
              <button class="btn btn-primary"> Log In </button>
              <button class="btn dropdown-toggle" data-toggle="dropdown">
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                <li> Email </li>
                <li> Password </li>
                <li> Submit </li>
              </ul>
            </div>
        </nav>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"> </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title> <%= full_title(yield(:title)) %></title>
        <%= stylesheet_link_tag    "application", media: "all" %>
        <%= javascript_include_tag "application" %>
        <%= csrf_meta_tags %>
        <%= render 'layouts/shim' %>
    </head>

    <body>
        <%= render 'layouts/header' %>

        <div class="container">
          <%= yield %>
        </div>

        <%= render 'layouts/footer' %>
    </body>
</html>

app/views/pages/about/mission.html.erb
<% provide(:title, 'Mission') %>

<h1> Mission & Vision </h1>
<p> Chezzles Vision </p>

app/views/pages/dash.html.erb
<% provide(:title, 'Dash') %>
<div class="center hero-unit">
    <h1> Chezzles Dashboard </h1>
    <p> Welcome to Chezzles Dashboard </p>
</div>

app/views/pages/help/faq.html.erb
<% provide(:title, 'FAQ') %>

<h1> Frequently Asked Questions </h1>
<p> Chezzles FAQs </p>

app/views/pages/home.html.erb
<% provide(:title, '') %>
<div class="center hero-unit">
  <h1>Welcome to Chezzles</h1>
  <p> Chezzles Homepage </p>

  <%= link_to "Sign Up", '#', class: 'btn btn-large btn-primary' %>
  <p> It's Your Move! </p>
  <%= link_to "Admission Form", '#', class: 'btn btn-large btn-inverse' %>
</div>

app/views/pages/profile.html.erb
<% provide(:title, 'Profile') %>
<div class="center hero-unit">
    <h1>Profile </h1>
    <p> Chezzles Profile Page </p>
</div>